Repository trimox/angular-mdc-web, pull requests merged in 2018-11, with the labels that each got.

#1509 feat(mdcTextField): Add ability to set field readOnly
  demos/components/textfield-demo/textfield-demo.html
  demos/components/textfield-demo/textfield-demo.ts
  packages/textfield/text-field.ts
  test/textfield/textfield.test.ts
Labels: enhancement

#1526 docs(demos): Update demos
  demos/app-layout.html
  demos/app-layout.ts
  demos/components/dialog-demo/dialog-demo.html
  demos/components/dialog-demo/dialog-demo.ts
  demos/components/dialog-demo/dialog-example.module.ts
  demos/components/dialog-demo/dialog-form-demo.html
  demos/getting-started/cli-guide.html
  demos/getting-started/cli-guide.ts
  demos/getting-started/getting-started.html
  demos/getting-started/index.ts
  demos/home/home.html
  demos/routes.ts
  demos/sass/_demo.scss
  demos/sass/_dialog.scss
  demos/sass/_docs.scss
  demos/sass/_global.scss
  demos/sass/_layout.scss
  demos/sass/_top-app-bar.scss
  demos/sass/app.scss
Labels: documentation

#1562 fix(list): Fix font size + placement for avatar graphic
  packages/material-components-web/scss/list/_mixins.scss
  packages/material-components-web/scss/list/mdc-list.scss
Labels: mdc-web-update

#1567 fix(text-field): Use setTimeout for recomputing svg path
  packages/textfield/text-field.ts
Labels: bug
