Repository trimox/angular-mdc-web, pull requests merged in 2020-02, with the labels that each got.

#2057 docs: Improve Sass module guides
  README.md
  demos/src/app/components/image-list-demo/examples.html
  demos/src/app/components/theme-docs/theme.ts
  demos/src/app/components/typography-demo/sass.html
  demos/src/app/components/typography-demo/typography-demo.ts
  demos/src/app/getting-started/getting-started.html
  demos/src/app/getting-started/getting-started.ts
  demos/src/app/shared.module.ts
  demos/src/app/shared/component-viewer/component-viewer.ts
  demos/src/app/shared/example-viewer/index.ts
  demos/src/index.html
  demos/src/styles/_list.scss
  docs/getting-started.md
Labels: documentation

#2072 docs: Minor improvements
  demos/src/app/app-routing.module.ts
  demos/src/app/components/menu-surface-demo/routing.module.ts
  demos/src/app/components/menu-surface/api.html
  demos/src/app/components/menu-surface/examples.html
  demos/src/app/components/menu-surface/menu-surface.ts
  demos/src/app/components/menu-surface/module.ts
  demos/src/app/components/menu-surface/routing.module.ts
  demos/src/app/components/menu-surface/sass.html
  demos/src/app/components/shape/module.ts
  demos/src/app/components/shape/routing.module.ts
  demos/src/app/components/shape/shape.ts
  demos/src/app/components/shape/usage.html
  demos/src/styles/_icon-button.scss
Labels: documentation

#2006 ci: Github Actions 🎉
  .github/workflows/master.yml
  .github/workflows/test.yml
Labels: internal

#2089 feat(icon): Allow viewBox to be configured when registering icons
  demos/src/app/components/icon/api.html
  demos/src/app/components/icon/icon.ts
  packages/icon/icon-registry.ts
  test/icon/icon.test.ts
Labels: enhancement

#2101 docs(card): Code cleanup
  demos/src/app/app-routing.module.ts
  demos/src/app/components/card-demo/card.module.ts
  demos/src/app/components/card-demo/routing.module.ts
  demos/src/app/components/card/api.html
  demos/src/app/components/card/card.ts
  demos/src/app/components/card/examples.html
  demos/src/app/components/card/module.ts
  demos/src/app/components/card/routing.module.ts
  demos/src/app/components/card/sass.html
Labels: documentation

#2102 fix(docs): Enable AOT build optimizer
  demos/angular.json
  demos/src/app/components/select/examples.html
  demos/src/app/components/select/select.ts
Labels: bug, documentation

#2127 docs(typography): Overriding global font family
  demos/src/app/app-routing.module.ts
  demos/src/app/components/typography-demo/routing.module.ts
  demos/src/app/components/typography-demo/typography.module.ts
  demos/src/app/components/typography/api.html
  demos/src/app/components/typography/examples.html
  demos/src/app/components/typography/module.ts
  demos/src/app/components/typography/routing.module.ts
  demos/src/app/components/typography/sass.html
  demos/src/app/components/typography/typography.ts
  test/typography/typography.test.ts
Labels: documentation
